version: "3.1"
services:
  app:
    image: splitter
    ports:
      - "9000:9000"
    depends_on:
      - database
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=splitter"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=pw"
<<<<<<< HEAD


=======
>>>>>>> working
